### ISSUE TITLE
Request: Dark theme

### ISSUE THREAD

**Issue by EC-O-DE** [Rob--W/crxviewer#40]
Could we have a dark theme?

And color coding?

:)

**Comment by Rob--W** [comment]
Pull requests are welcome.

Things that need to be extended:

- Main UI: https://github.com/Rob--W/crxviewer/blob/master/src/crxviewer.less
- Syntax highlighting: https://github.com/Rob--W/crxviewer/blob/master/src/lib/prettify/prettify.css
- Search result highlighting: https://github.com/Rob--W/crxviewer/blob/master/src/search-tools.less

Preferably as a new CSS file that can be applied after the other style sheets, using similar selectors as the other style sheets.

**Comment by atomGit** [comment]
a quick and dirty dark theme...

load the add-on and copy the url, then in /chrome/userContent.css replace `<url>` with the one you copied...

```css
@-moz-document url("<url>") {
    body {
        filter: invert(90%) !important;
        background: #2a2a2a !important;
    }
}
```
